language: node_js

os: osx

node_js:
  - 8
  - 6
  
script:
  - npm run test --coverage
  - npm run build

notifications:
  email:
    on_failure: change

after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$repo_token npm run coveralls

cache:
  yarn: true
  directories:
    - node_modules
